/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mutliSigSol from "./MutliSig.sol";
export type { mutliSigSol };
export type { IMultiSigWallet } from "./IMultiSigWallet";
export type { MultiSigWallet } from "./MultiSigWallet";
export type { StablecoinImpl } from "./StablecoinImpl";
