/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mutliSigSol from "./MutliSig.sol";
export { IMultiSigWallet__factory } from "./IMultiSigWallet__factory";
export { MultiSigWallet__factory } from "./MultiSigWallet__factory";
export { StablecoinImpl__factory } from "./StablecoinImpl__factory";
